services:
  # Main Discord bot with integrated cookie extraction
  robustty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robustty-bot
    restart: unless-stopped
    network_mode: host  # OrbStack optimization - use host networking
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - APIFY_API_KEY=${APIFY_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SEARCH_TIMEOUT=${SEARCH_TIMEOUT:-30}
      - STREAM_TIMEOUT=${STREAM_TIMEOUT:-300}
      - MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-100}
      - REDIS_URL=redis://localhost:6379
      - COOKIE_REFRESH_INTERVAL=7200  # 2 hours in seconds
    volumes:
      # Mount host Brave browser data for cookie extraction
      - "${HOME}/Library/Application Support/BraveSoftware/Brave-Browser:/host-brave:ro"
      # App data persistence
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - robustty-cookies:/app/cookies
    depends_on:
      - redis

  # Redis for caching (OrbStack optimized)
  redis:
    image: redis:7-alpine
    container_name: robustty-redis
    restart: unless-stopped
    network_mode: host  # OrbStack optimization
    volumes:
      - robustty-redis-data:/data
    command: redis-server --appendonly yes --port 6379

volumes:
  robustty-cookies:
    driver: local
  robustty-redis-data:
    driver: local