services:
  # Main Discord bot
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
      args:
        - BUILDKIT_PROGRESS=plain
        - DOCKER_BUILDKIT=1
    container_name: robustty-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SEARCH_TIMEOUT=${SEARCH_TIMEOUT:-30}
      - STREAM_TIMEOUT=${STREAM_TIMEOUT:-300}
      - MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-100}
      - ODYSEE_ENABLED=${ODYSEE_ENABLED:-false}
      - RUMBLE_ENABLED=${RUMBLE_ENABLED:-false}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - cookies:/app/cookies:ro
    depends_on:
      - redis
      - stream-service
    networks:
      - bot-network

  # Cookie extraction service
  cookie-extractor:
    build:
      context: .
      dockerfile: docker/cookie-extractor/Dockerfile
    container_name: robustty-cookies
    restart: unless-stopped
    volumes:
      - cookies:/app/cookies
      # Browser profile path is optional - comment out if not using
      # - ${BROWSER_PROFILE_PATH}:/browser/profile:ro
    environment:
      - REFRESH_INTERVAL=${COOKIE_REFRESH_INTERVAL}
      - DISPLAY=:99
    networks:
      - bot-network

  # Stream extraction service
  stream-service:
    build:
      context: .
      dockerfile: docker/stream-service/Dockerfile
    container_name: robustty-stream
    restart: unless-stopped
    ports:
      - "${STREAM_PORT:-5001}:5000"
    volumes:
      - cookies:/app/cookies:ro
      - ./data/cache:/app/cache
    environment:
      - FLASK_ENV=production
      - USE_RUMBLE_EXTRACTOR=${USE_RUMBLE_EXTRACTOR:-false}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
    networks:
      - bot-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: robustty-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - bot-network

volumes:
  cookies:
  redis-data:

networks:
  bot-network:
    driver: bridge