#!/bin/bash

# DNS Fix Script for Robustty VPS
# Automatically fix common DNS resolution issues on VPS
# Usage: sudo ./scripts/fix-vps-dns.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root (use sudo)"
        echo "Usage: sudo $0"
        exit 1
    fi
}

# Backup current DNS configuration
backup_dns_config() {
    print_info "Backing up current DNS configuration..."
    
    if [ -f /etc/resolv.conf ]; then
        cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d-%H%M%S)
        print_success "DNS configuration backed up"
    fi
    
    if [ -f /etc/systemd/resolved.conf ]; then
        cp /etc/systemd/resolved.conf /etc/systemd/resolved.conf.backup.$(date +%Y%m%d-%H%M%S)
        print_success "systemd-resolved configuration backed up"
    fi
}

# Fix DNS resolution by adding reliable public DNS servers
fix_dns_servers() {
    print_info "Adding reliable public DNS servers..."
    
    # Test which DNS servers are fastest
    DNS_SERVERS=("8.8.8.8" "1.1.1.1" "8.8.4.4" "1.0.0.1" "208.67.222.222")
    WORKING_DNS=()
    
    for dns in "${DNS_SERVERS[@]}"; do
        if ping -c 1 -W 2 "$dns" >/dev/null 2>&1; then
            WORKING_DNS+=("$dns")
            print_success "DNS server $dns is reachable"
        else
            print_warning "DNS server $dns is not reachable"
        fi
    done
    
    if [ ${#WORKING_DNS[@]} -eq 0 ]; then
        print_error "No public DNS servers are reachable - network connectivity issue"
        return 1
    fi
    
    # Update /etc/resolv.conf
    print_info "Updating /etc/resolv.conf..."
    {
        echo "# Generated by fix-vps-dns.sh - $(date)"
        echo "# Backup available at /etc/resolv.conf.backup.*"
        for dns in "${WORKING_DNS[@]:0:3}"; do  # Use top 3 working DNS servers
            echo "nameserver $dns"
        done
        # Add search domains if they existed before
        if [ -f /etc/resolv.conf.backup.* ]; then
            grep "^search\|^domain" /etc/resolv.conf.backup.* 2>/dev/null | head -2 || true
        fi
    } > /etc/resolv.conf
    
    print_success "Updated /etc/resolv.conf with working DNS servers"
}

# Configure systemd-resolved if present
fix_systemd_resolved() {
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        print_info "Configuring systemd-resolved..."
        
        # Update systemd-resolved configuration
        cat > /etc/systemd/resolved.conf << EOF
# Generated by fix-vps-dns.sh - $(date)
[Resolve]
DNS=8.8.8.8 1.1.1.1 8.8.4.4
FallbackDNS=1.0.0.1 208.67.222.222
Domains=~.
LLMNR=yes
MulticastDNS=yes
DNSSEC=allow-downgrade
DNSOverTLS=no
Cache=yes
DNSStubListener=yes
EOF
        
        # Restart systemd-resolved
        systemctl restart systemd-resolved
        print_success "systemd-resolved configured and restarted"
        
        # Ensure /etc/resolv.conf points to systemd-resolved
        if [ ! -L /etc/resolv.conf ] || [ "$(readlink /etc/resolv.conf)" != "../run/systemd/resolve/stub-resolv.conf" ]; then
            ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
            print_success "Linked /etc/resolv.conf to systemd-resolved"
        fi
    else
        print_info "systemd-resolved is not active, skipping"
    fi
}

# Fix network configuration
fix_network_config() {
    print_info "Checking network configuration..."
    
    # Ensure network interface is up
    for interface in $(ls /sys/class/net/ | grep -v lo); do
        if ! ip link show "$interface" | grep -q "state UP"; then
            print_warning "Network interface $interface is down, attempting to bring up..."
            ip link set "$interface" up || print_error "Failed to bring up $interface"
        else
            print_success "Network interface $interface is up"
        fi
    done
    
    # Check default route
    if ! ip route show | grep -q "default"; then
        print_error "No default route found - this may cause connectivity issues"
        print_info "Available routes:"
        ip route show
    else
        print_success "Default route is configured"
    fi
}

# Test DNS resolution after fixes
test_dns_resolution() {
    print_info "Testing DNS resolution after fixes..."
    
    DISCORD_ENDPOINTS=("gateway-us-east1-d.discord.gg" "discord.com" "google.com")
    ALL_RESOLVED=true
    
    for endpoint in "${DISCORD_ENDPOINTS[@]}"; do
        if nslookup "$endpoint" >/dev/null 2>&1; then
            print_success "DNS resolution OK for $endpoint"
        else
            print_error "DNS resolution still failing for $endpoint"
            ALL_RESOLVED=false
        fi
    done
    
    # Test HTTPS connectivity to Discord
    if command -v nc >/dev/null 2>&1; then
        if timeout 10 nc -z gateway-us-east1-d.discord.gg 443 >/dev/null 2>&1; then
            print_success "HTTPS connectivity to Discord gateway is working"
        else
            print_error "HTTPS connectivity to Discord gateway is still failing"
            ALL_RESOLVED=false
        fi
    fi
    
    return $ALL_RESOLVED
}

# Configure firewall to allow DNS and HTTPS
fix_firewall() {
    print_info "Configuring firewall rules..."
    
    # UFW configuration
    if command -v ufw >/dev/null 2>&1; then
        print_info "Configuring UFW firewall..."
        ufw allow out 53 comment "Allow outbound DNS" >/dev/null 2>&1 || true
        ufw allow out 443 comment "Allow outbound HTTPS" >/dev/null 2>&1 || true
        ufw allow out 80 comment "Allow outbound HTTP" >/dev/null 2>&1 || true
        print_success "UFW rules configured"
    fi
    
    # iptables configuration (if no UFW)
    if command -v iptables >/dev/null 2>&1 && ! command -v ufw >/dev/null 2>&1; then
        print_info "Configuring iptables firewall..."
        # Allow outbound DNS
        iptables -A OUTPUT -p udp --dport 53 -j ACCEPT >/dev/null 2>&1 || true
        iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT >/dev/null 2>&1 || true
        # Allow outbound HTTPS/HTTP
        iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT >/dev/null 2>&1 || true
        iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT >/dev/null 2>&1 || true
        print_success "iptables rules configured"
    fi
}

# Main execution
main() {
    echo -e "${BLUE}🔧 Robustty VPS DNS Fix Script${NC}"
    echo -e "${BLUE}==============================${NC}"
    echo ""
    
    check_root
    backup_dns_config
    fix_firewall
    fix_network_config
    fix_dns_servers
    fix_systemd_resolved
    
    echo ""
    print_info "Waiting 5 seconds for DNS changes to take effect..."
    sleep 5
    
    if test_dns_resolution; then
        echo ""
        print_success "🎉 DNS resolution has been fixed successfully!"
        print_info "Your Discord bot should now be able to connect properly."
    else
        echo ""
        print_error "Some DNS issues persist. Additional troubleshooting may be needed."
        print_info "Check the following:"
        echo "  1. VPS provider firewall/security groups"
        echo "  2. Network interface configuration"
        echo "  3. Contact VPS support if issues persist"
    fi
    
    echo ""
    print_info "DNS configuration summary:"
    echo "  - Current DNS servers: $(grep nameserver /etc/resolv.conf | awk '{print $2}' | tr '\n' ' ')"
    echo "  - Backup files created in /etc/ with .backup.* extension"
    echo "  - Firewall rules updated to allow DNS and HTTPS traffic"
    echo ""
    print_info "To revert changes, restore from backup files:"
    echo "  sudo cp /etc/resolv.conf.backup.* /etc/resolv.conf"
}

# Run the fix
main "$@"