name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-timeout pytest-html pytest-cov
    
    - name: Run Rumble Integration Tests
      env:
        APIFY_API_KEY: ${{ secrets.APIFY_API_KEY }}
      run: |
        pytest tests/integration/test_rumble_integration.py -v --tb=short --junit-xml=test-results/rumble-integration.xml
      continue-on-error: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
    
    - name: Generate test report
      if: always()
      run: |
        pytest tests/integration --html=report.html --self-contained-html
    
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: integration-test-report
        path: report.html